apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
  namespace: web-service-deployment
  labels:
    app: web-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:
      labels:
        app: web-service
    spec:
      containers:
      - name: web-service
        image: 091590067827.dkr.ecr.eu-central-1.amazonaws.com/web-service:latest
        ports:
        - name: http
          containerPort: 80
