---
galaxy_info:
  role_name: ansible
  namespace: core_devops
  author: nordo80
  description: Install and configure Prometheus
  company: local
  license: license
  min_ansible_version: 1.2
  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags: []

dependencies: []
